export const MESSAGE_ID = 'MessageId'
export const ROOM_ID = 'RoomId'
export const CONTENT = 'Content'
export const TYPE = 'Type'
export const TIME_CREATED = 'TimeCreated'
export const USER_ID = 'UserId'