export const SET_MEMBERS = 'SET_MEMBERS'
export const SET_MESSAGES = 'SET_MESSAGES'
export const ADD_MESSAGE = 'ADD_MESSAGE'
export const SET_ACTIVE_ROOM = 'SET_ACTIVE_ROOM'
export const SET_ROOMS = 'SET_ROOMS'
export const SET_ROOMS_INFO = 'SET_ROOMS_INFO'
